### ISSUE TITLE
The characters do not work, with the A3 theme on.

### ISSUE THREAD

**Issue by Yoshimitsu89** [Curilang/DDR-A3-THEME#25]
Hello, I have a problem when playing the A3 theme, when I go to play a song the characters do not appear, I have touched all kinds of options, but without a correct result, I use itgmania, and with that theme, the characters appear correctly I hope you can help me, greetings.

**Comment by SchneiderAFX** [comment]
if you're using outfox, sadly there's not much we can do, because the character system too out-of-date to work properly on OF, and it seems that the author doesn't want to update them to work properly on other than 5.1/ITGmania (and he doesn't want any help or even feedback on that matter, believe me, we tried).

**Comment by Yoshimitsu89** [comment]
Thanks for your help!!
